name: drink_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.13
  flutter_svg: ^2.0.10+1
  pinput: ^3.0.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_native_splash:
  color: "#C67C4E"
  image: assets/app_icon/app_icon.png
  android_12:
    color: "#C67C4E"
    image: assets/app_icon/app_icon.png



flutter:
  uses-material-design: true

  assets:
    - assets/on_boarding/
    - assets/icons/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
